FROM nginx
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./my.js /usr/share/nginx/html/my.js
COPY ./mystyle.css /usr/share/nginx/html/mystyle.css
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
